# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='location',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
