# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0002_outlet_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outlet',
            old_name='location',
            new_name='address',
        ),
        migrations.AddField(
            model_name='outlet',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outlet',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outlet',
            name='toy_types',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='outlet',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
