# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0003_auto_20171002_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='last_update',
            field=models.DateField(blank=True, null=True),
        ),
    ]
