# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0004_auto_20171002_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='category',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
